// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QyonAdventureWorks.Infra.MySql;

namespace QyonAdventureWorks.Infra.MySql.Migrations
{
    [DbContext(typeof(QyonAdventureWorksContext))]
    partial class QyonAdventureWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QyonAdventureWorks.Core.Entities.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("QyonAdventureWorks.Core.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BodyAvarageTemperature")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("QyonAdventureWorks.Core.Entities.RaceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("TimeSpent")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("DriverId");

                    b.ToTable("RaceHistories");
                });

            modelBuilder.Entity("QyonAdventureWorks.Core.Entities.RaceHistory", b =>
                {
                    b.HasOne("QyonAdventureWorks.Core.Entities.Circuit", "Circuit")
                        .WithMany("RaceHistories")
                        .HasForeignKey("CircuitId");

                    b.HasOne("QyonAdventureWorks.Core.Entities.Driver", "Driver")
                        .WithMany("RaceHistories")
                        .HasForeignKey("DriverId");
                });
#pragma warning restore 612, 618
        }
    }
}
